; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:gamepad_controller]
platform = espressif32@6.10.0
framework = arduino
board = esp32dev
board_build.partitions = huge_app.csv
board_build.mcu = esp32
board_build.f_cpu = 240000000L
build_src_filter = +<gamepad_controller.cpp>
platform_packages = 
    framework-arduinoespressif32@https://github.com/maxgerhardt/pio-framework-bluepad32/archive/refs/heads/main.zip
lib_deps = 
    agdl/Base64@^1.0.0
monitor_speed = 115200
monitor_port = /dev/cu.usbserial-5B310274181
upload_port = /dev/cu.usbserial-5B310274181

[env:espnow_controller]
platform = espressif32@6.10.0
framework = arduino
board = esp32dev
board_build.partitions = huge_app.csv
board_build.mcu = esp32
board_build.f_cpu = 240000000L
build_src_filter = +<espnow_controller.cpp>
lib_deps = 
    adafruit/Adafruit SSD1306 @ ^2.5.9
    adafruit/Adafruit GFX Library @ ^1.11.9
monitor_speed = 115200
monitor_port = /dev/cu.usbserial-5B310274161
upload_port = /dev/cu.usbserial-5B310274161
; Thats a test integration, no need to use this for the final version. --- IGNORE ---
[env:espnow_slave]
platform = espressif32@6.10.0
framework = arduino
board = esp32dev
board_build.partitions = huge_app.csv
board_build.mcu = esp32
board_build.f_cpu = 240000000L
build_src_filter = +<espnow_slave.cpp>
lib_deps = madhephaestus/ESP32Servo@^1.2.1
monitor_speed = 115200
monitor_port = /dev/cu.usbserial-120
upload_port = /dev/cu.usbserial-120
; Thats a test integration, no need to use this for the final version. --- IGNORE ---
[env:espnow_slave2]
platform = espressif32@6.10.0
framework = arduino
board = esp32dev
board_build.partitions = huge_app.csv
board_build.mcu = esp32
board_build.f_cpu = 240000000L
build_src_filter = +<espnow_slave2.cpp> +<EspNowRCReceiver.cpp>
lib_deps = madhephaestus/ESP32Servo@^1.2.1
monitor_speed = 115200
monitor_port = /dev/cu.usbserial-10
upload_port = /dev/cu.usbserial-10


[env:MiniDumpV2]
platform = espressif32@6.10.0
framework = arduino
board = esp32dev
board_build.partitions = huge_app.csv
board_build.mcu = esp32
board_build.f_cpu = 240000000L
build_src_filter = +<MiniDumpV2.cpp> +<EspNowRCReceiver.cpp>
lib_deps = madhephaestus/ESP32Servo@^1.2.1
monitor_speed = 115200
monitor_port = /dev/cu.usbserial-11410
upload_port = /dev/cu.usbserial-11410

[env:MiniSkiddi]
platform = espressif32@6.10.0
framework = arduino
board = esp32dev
board_build.partitions = huge_app.csv
board_build.mcu = esp32
board_build.f_cpu = 240000000L
build_src_filter = +<MiniSkiddi.cpp> +<EspNowRCReceiver.cpp>
lib_deps = madhephaestus/ESP32Servo@^1.2.1
monitor_speed = 115200
monitor_port = /dev/cu.usbserial-11410
upload_port = /dev/cu.usbserial-11410

[env:Excavator]
platform = espressif32@6.10.0
framework = arduino
board = esp32dev
board_build.partitions = huge_app.csv
board_build.mcu = esp32
board_build.f_cpu = 240000000L
build_src_filter = +<Excavator.cpp> +<EspNowRCReceiver.cpp>
lib_deps = 
    madhephaestus/ESP32Servo@^1.2.1
    adafruit/Adafruit MCP23017 Arduino Library@^2.3.2
monitor_speed = 115200
monitor_port = /dev/cu.usbserial-11410
upload_port = /dev/cu.usbserial-11410

[env:MiniLoader]
platform = espressif32@6.10.0
framework = arduino
board = esp32dev
board_build.partitions = huge_app.csv
board_build.mcu = esp32
board_build.f_cpu = 240000000L
build_src_filter = +<MiniLoader.cpp> +<EspNowRCReceiver.cpp>
lib_deps = madhephaestus/ESP32Servo@^1.2.1
monitor_speed = 115200
monitor_port = /dev/cu.usbserial-11410
upload_port = /dev/cu.usbserial-11410


[env:MiniLoaderOrg]
platform = espressif32@6.10.0
framework = arduino
board = esp32dev
board_build.partitions = huge_app.csv
board_build.mcu = esp32
board_build.f_cpu = 240000000L
build_src_filter = +<MiniLoaderOrg.cpp>
platform_packages = 
    framework-arduinoespressif32@https://github.com/maxgerhardt/pio-framework-bluepad32/archive/refs/heads/main.zip
lib_deps = 
    agdl/Base64@^1.0.0
    madhephaestus/ESP32Servo@^1.2.1
monitor_speed = 115200
monitor_port = /dev/cu.usbserial-10
upload_port = /dev/cu.usbserial-10
