; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:skiddi]
platform = espressif32@6.10.0
board = esp32dev
framework = arduino
build_src_filter = +<recv.cpp>
board_build.partitions = huge_app.csv
lib_deps = madhephaestus/ESP32Servo@^1.2.1
monitor_speed = 115200
monitor_port = /dev/cu.usbserial-10
upload_port = /dev/cu.usbserial-10

[env:controller]
platform = espressif32@6.10.0
framework = arduino
board = esp32dev
board_build.partitions = huge_app.csv
board_build.mcu = esp32
board_build.f_cpu = 240000000L
build_src_filter = +<controller.cpp>
platform_packages = 
    framework-arduinoespressif32@https://github.com/maxgerhardt/pio-framework-bluepad32/archive/refs/heads/main.zip
lib_deps = 
    agdl/Base64@^1.0.0
monitor_speed = 115200
monitor_port = /dev/cu.usbserial-0001
upload_port = /dev/cu.usbserial-0001


[env:espnow_master]
platform = espressif32@6.10.0
framework = arduino
board = esp32dev
board_build.partitions = huge_app.csv
board_build.mcu = esp32
board_build.f_cpu = 240000000L
build_src_filter = +<espnow_master.cpp>
platform_packages = 
    framework-arduinoespressif32@https://github.com/maxgerhardt/pio-framework-bluepad32/archive/refs/heads/main.zip
lib_deps = 
    adafruit/Adafruit SSD1306 @ ^2.5.9
    adafruit/Adafruit GFX Library @ ^1.11.9
monitor_speed = 115200
monitor_port = /dev/cu.usbserial-0001
upload_port = /dev/cu.usbserial-0001

[env:espnow_slave]
platform = espressif32@6.10.0
framework = arduino
board = esp32dev
board_build.partitions = huge_app.csv
board_build.mcu = esp32
board_build.f_cpu = 240000000L
build_src_filter = +<espnow_slave.cpp>
monitor_speed = 115200
monitor_port = /dev/cu.usbserial-0001
upload_port = /dev/cu.usbserial-0001